#+Title: ReadMe

* hacktorio

Currently there are four functions wired out onto a command line. 

1. Create dot
2. Get the name of an id
3. Get the id of an name
4. Calculate the combined amount of items

It's help looks like this
#+BEGIN_SRC bash
  haskell client that gives info from reciepes list
  v 0.1 - by frosch03

  hacktorio [COMMAND] ... [OPTIONS]
    Return various information of factorio recieps

  Common flags:
       --argfilename=FILE  Factorio recieps (default: /tmp/export.json)
       --argatoms=ITEM     Atomar items (default:
                           - iron-plate
                           - copper-plate
                           - steel-plate
                           - uranium-238
                           - uranium-235)
    -? --help              Display help message
    -V --version           Print version information

  hacktorio create-dot [OPTIONS]
    Write the graph into a .dot file

    -n --node-id=INT       Integer id of the item

  hacktorio name-from-id [OPTIONS]
    Return the name of the item with given id

    -n --node-id=INT       Integer id of the item

  hacktorio combined-amount [OPTIONS]
    Calculate the combined amount of atomar r~esources of the item

    -n --node-id=INT       Integer id of the item

  hacktorio id-from-name [OPTIONS]
    Return the id of the item with given name

    -n --node-name=STRING  The item name
#+END_SRC

** Create Dot

With this function you get a .dot file, containing the build graph of
an item. That item is identified by it's node id, which is an integer
number. 

#+BEGIN_SRC bash
hacktorio create-dot -n 4
#+END_SRC

<<<<<<< HEAD
This produces =/tmp/assembling-machine-1.dot=, unfortunately currently
it's hardwired to =/tmp= and the item's name. You can create a .png
=======
This produces `/tmp/assembling-machine-1.dot`, unfortunately currently
it's hardwired to `/tmp` and the item's name. You can create a .png
>>>>>>> af01ef48aeb1812ed7452409816a965eecb1ec91
image if you have the graphviz tools installed via:

#+BEGIN_SRC bash
dot -Tpng -o /tmp/assembling-machine-1.png /tmp/assembling-machine-1.dot
#+END_SRC

** Name from id

To get the name of an item from its id, use this function:

#+BEGIN_SRC bash
hacktorio name-from-id -n 4
#+END_SRC

<<<<<<< HEAD
Which should return =assembling-machine-1=.
=======
Which should return `assembling-machine-1`.
>>>>>>> af01ef48aeb1812ed7452409816a965eecb1ec91

** Id from name

The other way round, to get the id of an item from its name, use this
function:

#+BEGIN_SRC bash
hacktorio id-from-name -n assembling-machine-1
#+END_SRC

<<<<<<< HEAD
This should return =4=. Note, that you have to type the exact name. 
=======
This should return `4`. Note, that you have to type the exact name. 
>>>>>>> af01ef48aeb1812ed7452409816a965eecb1ec91

** Combined Amount

The combined amount of an item returns the amount of each atomic item,
that is needed in order to produce one of the given item. E.g. for one
<<<<<<< HEAD
=iron-gear-wheel= you need two =iron-plate=. So,
=======
`iron-gear-wheel` you need two `iron-plate`. So,
>>>>>>> af01ef48aeb1812ed7452409816a965eecb1ec91

#+BEGIN_SRC bash
hacktorio combined-amount -n 69
#+END_SRC

<<<<<<< HEAD
should return 11.5, as it is build in total of 11.5 =iron-plate=. 
=======
should return 11.5, as it is build in total of 11.5 `iron-plate`. 
>>>>>>> af01ef48aeb1812ed7452409816a965eecb1ec91

** Example usage

#+BEGIN_SRC bash
# ./hacktorio id-from-name -n iron-gear-wheel
Just 2

# ./hacktorio combined-amount -n 2
[("iron-plate",2.0)]

# ./hacktorio name-from-id -n 69
Just "fast-transport-belt"

# ./hacktorio combined-amount -n 69
[("iron-plate",11.5)]
#+END_SRC
